### PR TITLE
Merge with django-solo-1.1.2

### PR DESCRIPTION
**Pull request by frnhr**
This is a pretty straightfoward merge with the latest django-solo. No conflicts (other then `CHANGES` file and version numbers).

### CODE REVIEW

**Comment by gbezyuk** [comment]
Merged. Thank you for your work!

**Comment by frnhr** [comment]
My pleasure! Any chance for a PyPI release?

**Comment by gbezyuk** [comment]
@frnhr sure. In a moment.

**Comment by gbezyuk** [comment]
@frnhr done ;)

**Pull request merged**
